# Generated by Django 4.2 on 2023-05-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_upload_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=5)),
                ('product_description', models.CharField(max_length=100)),
                ('index_photo', models.FileField(upload_to='index_photo')),
                ('left_side_photo', models.FileField(upload_to='left_side_photo')),
                ('right_side_photo', models.FileField(upload_to='right_side_photo')),
                ('up_photo', models.FileField(upload_to='up_photo')),
                ('down_photo', models.FileField(upload_to='down_photo')),
                ('product_for', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
