# Generated by Django 4.2 on 2023-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0003_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
