# Generated by Django 4.2 on 2023-05-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0005_login_details_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_details',
            name='cart',
        ),
    ]
