# Generated by Django 4.2 on 2023-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0006_remove_login_details_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
