# Generated by Django 4.2 on 2023-05-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0007_cart_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_data',
        ),
        migrations.AddField(
            model_name='login_details',
            name='cart',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
