# Generated by Django 4.2 on 2023-05-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0008_delete_cart_data_login_details_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_details',
            name='cart',
        ),
    ]
