# Generated by Django 4.2 on 2023-05-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0010_cart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='index_photo',
            field=models.FileField(default=0, upload_to='cart_index'),
        ),
        migrations.AddField(
            model_name='cart_data',
            name='product_description',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='cart_data',
            name='product_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='cart_data',
            name='product_price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cart_data',
            name='product_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cart_data',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
