# Generated by Django 4.2 on 2023-05-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0012_alter_cart_data_index_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_data',
            old_name='index_photo',
            new_name='cart_index',
        ),
    ]
