# Generated by Django 4.2 on 2023-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0013_rename_index_photo_cart_data_cart_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='cart_index',
            field=models.FileField(default=0, max_length=50, upload_to=''),
        ),
    ]
