# Generated by Django 4.2 on 2023-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0014_alter_cart_data_cart_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_upload_database',
            name='seller_id',
            field=models.CharField(default='seller@gmail.com', max_length=50),
        ),
    ]
