# Generated by Django 4.2 on 2023-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0015_product_upload_database_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='checkbox_checked',
            field=models.CharField(default='on', max_length=10),
        ),
    ]
