# Generated by Django 4.2 on 2023-06-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0016_login_details_checkbox_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='checkbox_checked',
            field=models.CharField(default='onn', max_length=10),
        ),
    ]
