# Generated by Django 4.2 on 2023-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0017_alter_login_details_checkbox_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='checkbox_checked',
            field=models.CharField(default='on', max_length=10),
        ),
    ]
