# Generated by Django 4.2 on 2023-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swadeshimart', '0019_address_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_data',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
